"use strict";var promoMenuItems;var dates;$(document).ready(function(){if($(".selectize").length){$(".selectize").selectize()}
$('body').on('change','#calendar-interval',function(){if(vueApp){vueApp.newProfile[$(this).attr('name')]=$(this).val()}});if($(".reviews-items").length){$(".reviews-items").owlCarousel({margin:30,autoWidth:!1,items:1,loop:!1,nav:!0,dots:!1});var $owl=$('.promo-menu-items');$owl.children().each(function(index){$(this).attr('data-position',index)});$(".promo-menu-items").owlCarousel({margin:30,autoWidth:!1,items:2,center:!0,nav:!0,dots:!0,dotsData:!0,responsiveClass:!0,responsive:{1450:{items:3},577:{items:2,stagePadding:0,},0:{margin:10,items:1,stagePadding:30,autoWidth:!1,center:!1,},}});$(document).on('click','.owl-item>div',function(){var $speed=300;$owl.trigger('to.owl.carousel',[$(this).data('position'),$speed])})}
if($(".main-banner-steps--mobile").length){$(".main-banner-steps--mobile").owlCarousel({margin:30,autoWidth:!1,items:1,center:!0,stagePadding:200,nav:!0,navText:["<svg width=\"29\" height=\"18\" viewBox=\"0 0 29 18\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n"+"<path d=\"M0.879883 8.99966L29.0011 8.99966M8.78897 0.899658L0.879883 8.99966L8.78897 0.899658ZM0.879883 8.99966L8.78897 17.0997L0.879883 8.99966Z\"/>\n"+"</svg>\n","<svg width=\"29\" height=\"18\" viewBox=\"0 0 29 18\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n"+"<path d=\"M28.1226 8.99973L0.00134969 8.99973M20.2135 17.0997L28.1226 8.99973L20.2135 17.0997ZM28.1226 8.99973L20.2135 0.899734L28.1226 8.99973Z\"/>\n"+"</svg>\n"],responsive:{600:{items:1,center:!0,stagePadding:150,},550:{items:1,center:!0,stagePadding:100,},500:{items:1,center:!0,stagePadding:100,},451:{margin:80,items:1,center:!0,stagePadding:160,},417:{margin:80,items:1,center:!0,stagePadding:150,},393:{margin:40,items:1,center:!1,stagePadding:120,},0:{margin:110,items:1,center:!0,stagePadding:80,},}});$(".reviews-items--mobile").owlCarousel({autoWidth:!1,items:1,center:!0,dots:!1,nav:!0,navText:["<svg width=\"29\" height=\"18\" viewBox=\"0 0 29 18\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n"+"<path d=\"M0.879883 8.99966L29.0011 8.99966M8.78897 0.899658L0.879883 8.99966L8.78897 0.899658ZM0.879883 8.99966L8.78897 17.0997L0.879883 8.99966Z\"/>\n"+"</svg>\n","<svg width=\"29\" height=\"18\" viewBox=\"0 0 29 18\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n"+"<path d=\"M28.1226 8.99973L0.00134969 8.99973M20.2135 17.0997L28.1226 8.99973L20.2135 17.0997ZM28.1226 8.99973L20.2135 0.899734L28.1226 8.99973Z\"/>\n"+"</svg>\n"]})}
$(".accordion .accordion-control").on("click",function(){return $(this).toggleClass("active"),$(this).parent().find(".accordion-content").slideToggle(),!1});initCalendar()});function guidGenerator(){var S4=function(){return(((1+Math.random())*0x10000)|0).toString(16).substring(1)};return(S4()+S4()+"-"+S4()+"-"+S4()+"-"+S4()+"-"+S4()+S4()+S4())}
function initCalendar(reg=''){var e={0:"Январь",1:"Февраль",2:"Март",3:"Апрель",4:"Май",5:"Июнь",6:"Июль",7:"Август",8:"Сентябрь",9:"Октябрь",10:"Ноябрь",11:"Декабрь"},t=(new Date).getMonth(),o=0===t?11:t-1,n=11===t?0:t+1,a=(new Date).getFullYear();if($("#calendar").length){$("#calendar").each(function(){var $this=$(this);var guid=guidGenerator();console.log($this);$this.on('datepicker-change',function(){var value=$this.val();if($this.data('interval')){$.ajax({url:'/ajax/timeslots.php?date='+value,success:function(response){var newVal=moment(value,'DD.MM.YYYY').add(1,'days');if(vueApp){vueApp.newProfile[$this.attr('name')]=value}
try{var data=JSON.parse(response);var s=$('#'+$this.data('interval'))[0].selectize;s.clearOptions();for(var i=0;i<data.length;i++){var t=data[i];s.addOption({value:t,text:t})}
s.setValue(data[0],!0);vueApp.newProfile.P_TIME=data[0];s.refreshOptions();if(!data.length){$this.val(newVal.format('DD.MM.YYYY'));$this.data("dateRangePicker").setStart(newVal.format('DD.MM.YYYY'));$this.trigger('datepicker-change')}}catch(e){console.log(e)}
$('.'+guid+' .perv-month').text(e[newVal.subtract(1,'months').format('M')]);$('.'+guid+' .current-month').text(e[newVal.format('M')]+', '+newVal.format('YYYY'));$('.'+guid+' .next-month').text(e[newVal.add(1,'months').format('M')])}})}else if(vueApp){vueApp.newProfile[$this.attr('name')]=value}});$this.dateRangePicker({autoClose:!0,disableTouchKeyboard:!0,readonly:"disabled",singleDate:!0,showShortcuts:!1,singleMonth:!0,language:"ru",startOfWeek:"monday",setValue:function(s){if(!$(this).is(':disabled')&&s!=$(this).val()){$(this).val(s)}},beforeShowDay:function(t,a,b,c,d){if(moment(t).isBefore(moment())&&!(moment().isSame(moment(t),'month')&&moment().isSame(moment(t),'day'))){return[!1,'','']}
if($this.data('disabled')&&!0){dates=JSON.parse($('#'+$this.data('disabled')).val());for(var i=0;i<dates.BLOCK_DAYS.length;i++){var dd=dates.BLOCK_DAYS[i];if(moment(dd,'DD.MM.YYYY').isSame(moment(t),'year')&&moment(dd,'DD.MM.YYYY').isSame(moment(t),'month')&&moment(dd,'DD.MM.YYYY').isSame(moment(t),'day')){return[!1,'','']}}}
return[!0,'','']},format:"DD.MM.YYYY",extraClass:guid,customTopBar:'\n                <div class="wrap-calendar-control">\n                    <div class="perv-month">'+e[o]+'</div>\n                    <div class="current-month">'+e[t]+", "+a+'</div>\n                    <div class="next-month">'+e[n]+"</div>\n                </div>\n            "});$this.attr('readonly','readonly');$('.'+guid+" .perv-month").click(function(){var val=$this.val();var newVal=moment(val,'DD.MM.YYYY').subtract(1,'months');if(moment(new Date()).diff(moment(newVal),'months',!0)>0){return!1}
$this.data("dateRangePicker").setStart(newVal.format('DD.MM.YYYY'));$('.'+guid+' .perv-month').text(e[newVal.subtract(1,'months').format('M')]);$('.'+guid+' .current-month').text(e[newVal.format('M')]+', '+newVal.format('YYYY'));$('.'+guid+' .next-month').text(e[newVal.add(1,'months').format('M')])});$('.'+guid+" .next-month").click(function(){var val=$this.val();var newVal=moment(val,'DD.MM.YYYY').add(1,'months');$this.data("dateRangePicker").setStart(newVal.format('DD.MM.YYYY'));$('.'+guid+' .perv-month').text(e[newVal.subtract(1,'months').format('M')]);$('.'+guid+' .current-month').text(e[newVal.format('M')]+', '+newVal.format('YYYY'));$('.'+guid+' .next-month').text(e[newVal.add(1,'months').format('M')])});$('.'+guid+" #del-select").on("change",function(){var e=$(this).val();$("#del-img-1").hide(),$("#del-img-2").hide(),$("#del-img-"+e).show()})})}}(function(){let not_price;let price_html;let product_price;let product_price2;let list;let plus_minus;let weight;let weight_number;function findSelect(list){for(let a=0;a<list.length;a++){if(list[a].classList.contains('selected')){return a+1}}
return}
function actionsPrice(value,not_price,price_html,list,plus_minus,weight,weight_number){let price;let price2;let price3;let weight_action;let select_number;if(list.length>2){plus_minus[1].classList.remove('icon-disactive')}
for(let i=0;i<plus_minus.length;i++){plus_minus[i].addEventListener('click',function(){const return_number=findSelect(list);if(i===0){if(return_number>1&&return_number!==undefined){select_number=return_number-1}}else if(i===1){if(return_number<=list.length-2&&return_number!==undefined){select_number=return_number+1}}
const not_product_price=document.querySelector('.js-two-buy .js-product-price');const not_product_price2=document.querySelector('.product-modify .js-product-price');console.log(not_product_price2);const not_price2=document.querySelector('.js-price2');price=Number(price_html);price2=Number(product_price);price3=Number(product_price2);if(weight_number){weight_action=Number(weight_number)}
if(select_number!==undefined){price*=select_number;price3*=select_number;if(!weight){price2*=select_number}
if(weight_action){weight_action*=select_number}}else{price*=1;price3*=1;if(!weight){price2*=1}
if(weight_action){weight_action*=1}}
not_price.innerHTML=String(price)+'₽';not_price2.innerHTML=String(price)+'₽';if(value===!0){not_product_price2.innerHTML=String(price3)+'₽'}
if(!weight){not_product_price.innerHTML=String(price2)+'₽'}
if(weight){weight[0].innerHTML='Вес блюда '+String(weight_action)+' г';weight[1].innerHTML='Вес блюда '+String(weight_action)+' г'}
if(select_number<=1&&!plus_minus[0].classList.contains('icon-disactive')){plus_minus[0].classList.add('icon-disactive');if(plus_minus[1].classList.contains('icon-disactive')){plus_minus[1].classList.remove('icon-disactive')}}else if(select_number>list.length-2){plus_minus[1].classList.add('icon-disactive');if(plus_minus[0].classList.contains('icon-disactive')){plus_minus[0].classList.remove('icon-disactive')}}else if(select_number>1&&select_number<=list.length-1){if(plus_minus[0].classList.contains('icon-disactive')){plus_minus[0].classList.remove('icon-disactive')}
if(plus_minus[1].classList.contains('icon-disactive')){plus_minus[1].classList.remove('icon-disactive')}}})}}
function removeSelected(){for(let a=0;a<list.length;a++){if(list[a].classList.contains('selected')){list[a].classList.remove('selected');return}}}
window.addEventListener('DOMContentLoaded',function(){const products=document.querySelectorAll('.js-show-product');let n_price=document.querySelectorAll('.js-price');if(products[0]){for(let i=0;i<products.length;i++){products[i].addEventListener('click',()=>{const interval=setInterval(()=>{not_price=document.querySelector('.js-price');if(not_price!==undefined&¬_price!==null){setTimeout(()=>{not_price=document.querySelector('.js-price');price_html=not_price.innerHTML.replace(/₽/g,'');list=document.querySelectorAll('.js-list');plus_minus=document.querySelectorAll('.js-plus-minus');weight=document.querySelectorAll('.js-weight');weight_number=weight[0].innerHTML.replace(/\D+/g,'');setTimeout(actionsPrice,10)},1000);clearInterval(interval)}},10)})}}else if(n_price[0]){const container=document.querySelector('.product-modify');not_price=container.querySelector('.js-price');price_html=not_price.innerHTML.replace(/₽/g,'');const not_product_price=container.querySelector('.js-product-price');product_price2=not_product_price.innerHTML.replace(/₽/g,'');list=container.querySelectorAll('.js-list');plus_minus=container.querySelectorAll('.js-plus-minus');weight=container.querySelectorAll('.js-weight');weight_number=weight[0].innerHTML.replace(/\D+/g,'');const value=!0;actionsPrice(value,not_price,price_html,list,plus_minus,weight,weight_number)}
if(n_price[1]){const container=document.querySelector('.js-two-buy');not_price=container.querySelector('.js-price');price_html=not_price.innerHTML.replace(/₽/g,'');const not_product_price=container.querySelector('.js-product-price');product_price=not_product_price.innerHTML.replace(/₽/g,'');list=container.querySelectorAll('.js-list');plus_minus=container.querySelectorAll('.js-plus-minus');let number_person;const value=!1;actionsPrice(value,not_price,price_html,list,plus_minus);for(let i=0;i<plus_minus.length;i++){plus_minus[i].addEventListener('click',function(){if(i===0&&!list[0].classList.contains('selected')){number_person=findSelect(list);removeSelected();list[number_person-2].classList.add('selected')}else if(i===1&&!list[list.length-1].classList.contains('selected')){number_person=findSelect(list);removeSelected();list[number_person].classList.add('selected')}})}}})})();(function(){window.addEventListener('DOMContentLoaded',function(){var buttons=document.querySelectorAll('.js-button');var moving_block=document.querySelector('.js-move');var time_buttons=300;var time_blocks=150;var containers=document.querySelectorAll('.js-container');var main_block=document.querySelector('.js-ingredients-recipes');var block_buttons=document.querySelector('.js-block-buttons');for(let i=0;i<buttons.length;i++){buttons[i].addEventListener('click',function(){var half_width=block_buttons.offsetWidth/2;if(!buttons[i].classList.contains('active')){for(let a=0;a<buttons.length;a++){if(buttons[a].classList.contains('active')){buttons[a].classList.remove('active')}}
buttons[i].classList.add('active');if(i>0){moving_block.classList.add('move-block-right');moving_block.style.left='0px';setTimeout(function(){moving_block.style.left=half_width+'px'},1);setTimeout(function(){moving_block.style.right='0px';moving_block.style.left='auto'},time_buttons)}else{moving_block.classList.remove('move-block-right');moving_block.style.left=half_width+'px';moving_block.style.right='auto';setTimeout(function(){moving_block.style.left='0px'},1);setTimeout(function(){moving_block.style.left='auto'},time_buttons)}
for(let b=0;b<containers.length;b++){if(containers[b].classList.contains('active')){containers[b].classList.remove('active');setTimeout(function(){containers[b].style.height='0px'},time_blocks)}
if(main_block){if(containers[b].classList.contains('js-recipe')&&!main_block.classList.contains('active')){main_block.classList.add('active')}else if(containers[b].classList.contains('js-recipe')&&main_block.classList.contains('active')){main_block.classList.remove('active')}}}
setTimeout(function(){containers[i].classList.add('active');containers[i].style.height='auto'},time_blocks)}})}})})()